#include <DFRobot_DF1201S.h>

/*
  Sketch generated by the Arduino IoT Cloud Thing 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int activeCount;
  bool commandStat;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <HardwareSerial.h>

#define RelayLight 17
DFRobot_DF1201S DF1201S;
HardwareSerial DF1201SSerial(1);

bool warningActive = false;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  DF1201SSerial.begin ( 115200, SERIAL_8N1, 3, 1 );
  
  //DF1201SSerial.begin(115200);
  while(!DF1201S.begin(DF1201SSerial)){
    Serial.println("Init failed, please check the wire connection!");
    delay(1000);
  }
  /*Set volume to 20*/
  DF1201S.setVol(/*VOL = */20);
  Serial.print("VOL:");
  /*Get volume*/
  Serial.println(DF1201S.getVol());
  /*Enter music mode*/
  DF1201S.switchFunction(DF1201S.MUSIC);
  /*Wait for the end of the prompt tone */
  delay(2000);
  /*Set playback mode to "repeat all"*/
  DF1201S.setPlayMode(DF1201S.ALLCYCLE);
  Serial.print("PlayMode:");
  /*Get playback mode*/
  Serial.println(DF1201S.getPlayMode());
  

  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();


  pinMode(RelayLight, OUTPUT);
  pinMode(0, INPUT);
  digitalWrite(0, LOW);

}

void loop() {
  ArduinoCloud.update();
  // Your code here
  if (commandStat == true) {
    digitalWrite(RelayLight, HIGH);
    if(warningActive==false){
      DF1201S.start();
      warningActive = true;
      delay(3000);      
    }
    
    
  } else {
    digitalWrite(RelayLight, LOW);
    if(warningActive==true){
      DF1201S.pause();
      warningActive = false;    
    }    
    
    
  }

}


/*
  Since CommandStat is READ_WRITE variable, onCommandStatChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCommandStatChange()  {
  // Add your code here to act upon CommandStat change

}

/*
  Since ActiveCount is READ_WRITE variable, onActiveCountChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onActiveCountChange()  {
  // Add your code here to act upon ActiveCount change
}
